vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.startofline = false
vim.opt.termguicolors = true
vim.opt.splitright = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.mouse = 'a'
vim.opt.updatetime = 250
vim.opt.cursorline = true
vim.cmd[[set fillchars+=diff:.]]
vim.wo.signcolumn= 'yes'
vim.opt.completeopt = 'menuone,noselect'
vim.g.telescope_changed_files_branch = 'master'
